[package]
name = "rust-audio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.2"
time = "0.1"

[profile.dev]
overflow-checks = false
